site_name: Technical Notes
site_author: Danyiel Colin
repo_name: DanEscher98/TechnicalNotes
repo_url: https://github.com/DanEscher98/TechnicalNotes
copyright: Copyright &copy; 2020 - 2023 Danyiel Colin
site_description: >-
  Notes about my technical discoveries and a couple of tutorials

theme:
  name: material
  font:
    text: Libre Baskerville
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: dark)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

    - media: "(prefers-color-scheme: light)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
  features:
    - content.code.copy
    - content.action.edit
    - content.action.view
    - navigation.footer
  highlightjs: true
  hljs_languages:
    - yaml
    - haskell
    - rust
    - python
    - bash
    - make

extra:
  generator: false

markdown_extensions:
  - codehilite
  - tables
  - fenced_code
  - def_list
  - smarty
  - sane_lists
  - attr_list
  - md_in_html
  - mkdocs_graphviz:   
      light_theme: 000000     # Default color of the graph in Light Theme
      dark_theme: FFFFFF      # Default color of the graph in Dark Theme
      color: 789ABC          
      bgcolor: none           # Transparent background
      graph_color: 789ABC     
      graph_fontcolor: 789ABC
      node_color: 789ABC     
      node_fontcolor: 789ABC 
      edge_color: 789ABC     
      edge_fontcolor: 789ABC  
  - toc:
      permalink: True
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.magiclink
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde

extra_javascript:
  - js/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://cdn.jsdelivr.net/gh/rod2ik/cdn@main/mkdocs/javascripts/massilia-graphviz.js

extra_css:
  - css/extra.css


plugins:
  - search
    #- section-index
  - literate-nav:
      nav_file: SUMMARY.md
